// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stringop.proto

package cmdpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringOP struct {
	Op                   int32    `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Param                string   `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringOP) Reset()         { *m = StringOP{} }
func (m *StringOP) String() string { return proto.CompactTextString(m) }
func (*StringOP) ProtoMessage()    {}
func (*StringOP) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d5e3a3bf0a54574, []int{0}
}

func (m *StringOP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringOP.Unmarshal(m, b)
}
func (m *StringOP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringOP.Marshal(b, m, deterministic)
}
func (m *StringOP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringOP.Merge(m, src)
}
func (m *StringOP) XXX_Size() int {
	return xxx_messageInfo_StringOP.Size(m)
}
func (m *StringOP) XXX_DiscardUnknown() {
	xxx_messageInfo_StringOP.DiscardUnknown(m)
}

var xxx_messageInfo_StringOP proto.InternalMessageInfo

func (m *StringOP) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *StringOP) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func init() {
	proto.RegisterType((*StringOP)(nil), "cmdpb.StringOP")
}

func init() { proto.RegisterFile("stringop.proto", fileDescriptor_0d5e3a3bf0a54574) }

var fileDescriptor_0d5e3a3bf0a54574 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0xcf, 0x2f, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0xce, 0x4d, 0x29,
	0x48, 0x92, 0xe2, 0x4d, 0x49, 0x4d, 0x4b, 0x2c, 0xcd, 0x29, 0x81, 0x88, 0x2a, 0x19, 0x70, 0x71,
	0x04, 0x83, 0xd5, 0xf9, 0x07, 0x08, 0xf1, 0x71, 0x31, 0xe5, 0x17, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xb0, 0x06, 0x31, 0xe5, 0x17, 0x08, 0x89, 0x70, 0xb1, 0x16, 0x24, 0x16, 0x25, 0xe6, 0x4a, 0x30,
	0x29, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x46, 0x4e, 0x5c, 0xdc, 0x30, 0x93, 0x8b, 0x8b, 0xca,
	0x84, 0x8c, 0xb9, 0xb8, 0xa0, 0x06, 0x14, 0xb8, 0xe4, 0x0b, 0xf1, 0xeb, 0x81, 0x6d, 0xd1, 0x83,
	0x99, 0x29, 0x25, 0x04, 0x15, 0x70, 0x81, 0xd8, 0x1a, 0x94, 0x5a, 0x5c, 0xa0, 0xc4, 0x90, 0xc4,
	0x06, 0xb6, 0xdc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x12, 0x80, 0xb8, 0xa4, 0x00, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StringopsrvClient is the client API for Stringopsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StringopsrvClient interface {
	StringOpDo(ctx context.Context, in *StringOP, opts ...grpc.CallOption) (*DefaultResp, error)
}

type stringopsrvClient struct {
	cc *grpc.ClientConn
}

func NewStringopsrvClient(cc *grpc.ClientConn) StringopsrvClient {
	return &stringopsrvClient{cc}
}

func (c *stringopsrvClient) StringOpDo(ctx context.Context, in *StringOP, opts ...grpc.CallOption) (*DefaultResp, error) {
	out := new(DefaultResp)
	err := c.cc.Invoke(ctx, "/cmdpb.stringopsrv/StringOpDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringopsrvServer is the server API for Stringopsrv service.
type StringopsrvServer interface {
	StringOpDo(context.Context, *StringOP) (*DefaultResp, error)
}

// UnimplementedStringopsrvServer can be embedded to have forward compatible implementations.
type UnimplementedStringopsrvServer struct {
}

func (*UnimplementedStringopsrvServer) StringOpDo(ctx context.Context, req *StringOP) (*DefaultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringOpDo not implemented")
}

func RegisterStringopsrvServer(s *grpc.Server, srv StringopsrvServer) {
	s.RegisterService(&_Stringopsrv_serviceDesc, srv)
}

func _Stringopsrv_StringOpDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringOP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringopsrvServer).StringOpDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdpb.stringopsrv/StringOpDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringopsrvServer).StringOpDo(ctx, req.(*StringOP))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stringopsrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdpb.stringopsrv",
	HandlerType: (*StringopsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StringOpDo",
			Handler:    _Stringopsrv_StringOpDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stringop.proto",
}
